/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orcamentos;

import javax.swing.JOptionPane;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.*;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Date;
import com.itextpdf.text.*;

/**
 *
 * @author geova_16fe4ev
 */
public class Orcamento_Tela extends javax.swing.JFrame {

    /**
     * Creates new form Ocamento_Tela
     */
    public Orcamento_Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PDF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Produto = new javax.swing.JTextField();
        Qtd = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ValorUN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PDF.setText("Gera PDF");
        PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFActionPerformed(evt);
            }
        });
        getContentPane().add(PDF);
        PDF.setBounds(300, 310, 100, 27);

        jLabel1.setText("Codigo Do Produto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(305, 30, 120, 20);

        Cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodActionPerformed(evt);
            }
        });
        getContentPane().add(Cod);
        Cod.setBounds(320, 50, 68, 26);

        jLabel2.setText("Produto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 90, 50, 16);

        Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(Produto);
        Produto.setBounds(250, 110, 220, 26);
        getContentPane().add(Qtd);
        Qtd.setBounds(320, 170, 68, 26);

        jLabel3.setText("Quantidade");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 150, 70, 16);

        jLabel4.setText("Valor Unitario");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 220, 80, 16);

        ValorUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorUNActionPerformed(evt);
            }
        });
        getContentPane().add(ValorUN);
        ValorUN.setBounds(310, 240, 75, 26);

        setSize(new java.awt.Dimension(704, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutoActionPerformed

    private void CodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodActionPerformed

    private void ValorUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorUNActionPerformed

    private void PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFActionPerformed
        // TODO add your handling code here:
        GerarPDF();
    }//GEN-LAST:event_PDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orcamento_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orcamento_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orcamento_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orcamento_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Orcamento_Tela().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cod;
    private javax.swing.JButton PDF;
    private javax.swing.JTextField Produto;
    private javax.swing.JSpinner Qtd;
    private javax.swing.JTextField ValorUN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void GerarPDF() {
        //Pega os dados da Tela
        String Codigo = (Cod.getText());
        String produto = (Produto.getText());
        int Quantidade = (int) (Qtd.getValue());
        String texto = ValorUN.getText();
        float valorFloat = Float.parseFloat(texto);
        //Faz a Soma da quantidade com o valor
        float TOTAL = Quantidade * valorFloat;
        JOptionPane.showMessageDialog(null, Codigo + "|" + produto + "|" + Quantidade + "|" + valorFloat + "|" + TOTAL);
        Document document = new Document();
        //Gerar Pdf
        try {
            PdfWriter.getInstance(document, new FileOutputStream("Orcamento.pdf"));
            //Inicia A edição ao PDF
            document.open();
            Date Data = new Date();
            DateFormat formatador = DateFormat.getDateInstance(DateFormat.FULL);
            document.add(new Paragraph(formatador.format(Data)));
            document.add(new Paragraph("Orçamento Univipax"));
            document.add(new Paragraph(" "));
            //Cria uma Tabela de 5 Colunas
            PdfPTable Tabela = new PdfPTable(5);
            PdfPCell coluna1 = new PdfPCell(new Paragraph("Código"));
            PdfPCell coluna2 = new PdfPCell(new Paragraph("Produto"));
            PdfPCell coluna3 = new PdfPCell(new Paragraph("Quantidade"));
            PdfPCell coluna4 = new PdfPCell(new Paragraph("Valor Unitário"));
            PdfPCell coluna5 = new PdfPCell(new Paragraph("Total"));
            //ADD O Texto nas colunas
            Tabela.addCell(coluna1);
            Tabela.addCell(coluna2);
            Tabela.addCell(coluna3);
            Tabela.addCell(coluna4);
            Tabela.addCell(coluna5);
            // Data row
            PdfPCell codigo = new PdfPCell(new Paragraph(Codigo));
            PdfPCell produto2 = new PdfPCell(new Paragraph(produto));
            PdfPCell quantidade = new PdfPCell(new Paragraph(String.valueOf(Quantidade)));
            PdfPCell valorUnitario = new PdfPCell(new Paragraph(String.valueOf(valorFloat)+" R$"));
            PdfPCell total = new PdfPCell(new Paragraph(String.valueOf(TOTAL)+" R$"));

            Tabela.addCell(codigo);
            Tabela.addCell(produto2);
            Tabela.addCell(quantidade);
            Tabela.addCell(valorUnitario);
            Tabela.addCell(total);

            document.add(Tabela);

        } catch (DocumentException | FileNotFoundException e) {
            System.out.println(e);
        } finally {
            document.close();
        }
        //Abrir Documento
        try {
            Desktop.getDesktop().open(new File("Orcamento.pdf"));
        } catch (IOException e) {
            System.out.println(e);

        }
    }
}
