/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orcamentos;


/**
 *
 * @author geova_16fe4ev
 */
public class TELA_DE_ESCOLHA extends javax.swing.JFrame {

    /**
     * Creates new form TELA_DE_ESCOLHA
     */
    public TELA_DE_ESCOLHA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Orcamento = new javax.swing.JButton();
        Gestao = new javax.swing.JButton();
        Estatistica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Orcamento.setText("Orçamento");
        Orcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrcamentoActionPerformed(evt);
            }
        });
        getContentPane().add(Orcamento);
        Orcamento.setBounds(330, 190, 120, 27);

        Gestao.setText("Gestão");
        getContentPane().add(Gestao);
        Gestao.setBounds(330, 240, 120, 27);

        Estatistica.setText("Estatística");
        getContentPane().add(Estatistica);
        Estatistica.setBounds(330, 290, 120, 27);

        setSize(new java.awt.Dimension(795, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrcamentoActionPerformed
        Orcamento_Tela Orca_tela= new Orcamento_Tela();
        this.dispose();
        Orca_tela.setVisible(true);
    }//GEN-LAST:event_OrcamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_DE_ESCOLHA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_DE_ESCOLHA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_DE_ESCOLHA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_DE_ESCOLHA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TELA_DE_ESCOLHA().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Estatistica;
    private javax.swing.JButton Gestao;
    private javax.swing.JButton Orcamento;
    // End of variables declaration//GEN-END:variables
}
